language: php

php:
  - 7.0

before_script:
  - mysql -e 'create database churchsermons_testing_db;'
  - cp .env.travis .env
  - composer self-update
  - composer update --no-interaction
  - php artisan migrate

script:
  - vendor/bin/phpunit